---
- name: Get and Extract Jamf Installer
  unarchive: 
    src: "https://s3.amazonaws.com/ul-devops/ansible-role-files/jamf-pro-installer-linux-10.6.0.zip"
    dest: "/tmp/"
    remote_src: yes

- name: Run Installer
  script: /tmp/jamfproinstaller.run -y 
